module.exports = ["Altere as configurações de idioma do seu telefone.",
"Ouça um podcast ou as notícias no idioma alvo.",
"Assista a um programa de TV que você gosta com legendas no idioma alvo",
"Rotule tudo o que você possui com post-its no idioma alvo",
"Cozinhe uma refeição usando receitas no idioma alvo ",
"Explore partes da internet no idioma alvo",
"Leia as notícias no idioma alvo",
"Treine seu cão ou gato no idioma alvo",
"Consiga um amigo por correspondência que mora em outro país.",
"Assista a filmes no idioma alvo.",
"Escreva sua lista de tarefas no idioma alvo",
"Pedir comida usando no idioma alvo",
"Jogue videogames em no idioma alvo.",
"Fale com seus colegas de trabalho no idioma alvo.",
"Crie um instagram para o seu alter ego no idioma alvo.",
"Comece a twittar no idioma alvo",
"Leia livros no idioma alvo.",
"Leia o BuzzFeed no idioma alvo",
"Junte-se a grupos do Facebook que falam o idioma alvo.",
"Ouça música no idioma alvo.",
"Aprenda a xingar no idioma alvo.",
"Faça um diário no idioma alvo."];